#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {
    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_init"

        "bash_aliases"
        "bash_autocompletion"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"

        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../os/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

clear

# Added by LM Studio CLI (lms)
export PATH="$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init - zsh)"

# Flutter - MUST be early to override Homebrew Dart
export PATH="$HOME/development/flutter/bin:$PATH"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

# Dart pub cache
export PATH="$HOME/.pub-cache/bin:$PATH"

# Gems from rbenv Ruby
export GEM_HOME="$HOME/.gem"
export PATH="$GEM_HOME/bin:$PATH"

# Java from Android Studio
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

# Android tools
export PATH="$HOME/Android/cmdline-tools/latest/bin:$PATH"

# LM Studio
export PATH="$PATH:/Users/sotiriskast/.lmstudio/bin"

# Homebrew - MUST be LAST
export PATH="$PATH:/opt/homebrew/bin"

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

