#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="gnome-screensaver-command --lock"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Advanced Packaging Tool`

alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty trash.

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open from the terminal.

alias o="xdg-open"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo apt-get update \
            && sudo apt-get upgrade -y"
alias up="sudo apt update \
            && sudo apt upgrade -y"
            
alias phpdock82 ="sudo systemctl stop nginx.service mariadb.service php7.4-fpm.service && cd ~/Documents/ideaseven/docker_project/phpdock/ && export PHP_VERSION=8.2 && make uplocal"
alias phpdock81 ="sudo systemctl stop nginx.service mariadb.service php7.4-fpm.service && cd ~/Documents/ideaseven/docker_project/phpdock/ && export PHP_VERSION=8.1 && make uplocal"
alias phpdock80 ="sudo systemctl stop nginx.service mariadb.service php7.4-fpm.service && cd ~/Documents/ideaseven/docker_project/phpdock/ && export PHP_VERSION=8.0 && make uplocal"
alias phpdock74 ="sudo systemctl stop nginx.service mariadb.service php7.4-fpm.service && cd ~/Documents/ideaseven/docker_project/phpdock/ && export PHP_VERSION=7.4 && make uplocal"
alias phpdock73 ="sudo systemctl stop nginx.service mariadb.service php7.4-fpm.service && cd ~/Documents/ideaseven/docker_project/phpdock/ && export PHP_VERSION=7.3 && make uplocal"
